# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourhockey_common', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
