# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ourhockey_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ourhockey_common.Person')),
                ('back_number', models.IntegerField(default=0)),
                ('duty', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=2)),
                ('player_level', models.CharField(default='03', max_length=2)),
                ('player_state', models.CharField(default='00', max_length=2)),
            ],
            bases=('ourhockey_common.person',),
        ),
    ]
