# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ourhockey_playermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourhockey_playermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_profile_photo',
            field=models.ImageField(default=datetime.datetime(2016, 2, 21, 11, 47, 25, 459006, tzinfo=utc), height_field='height', upload_to=ourhockey_playermanager.models.get_upload_to, verbose_name='player_profile_photo', width_field='width'),
            preserve_default=False,
        ),
    ]
