# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import ourhockey_playermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourhockey_playermanager', '0005_auto_20160221_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(upload_to=ourhockey_playermanager.models.get_upload_to),
        ),
    ]
